# Generated by Django 4.1 on 2022-08-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.IntegerField()),
                ('text2', models.IntegerField()),
                ('text3', models.IntegerField()),
            ],
        ),
    ]
