# Generated by Django 4.1 on 2022-08-27 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostInt',
        ),
    ]
